.\checkSirius.js
.\cmdlib.wsc
.\eventquery.vbs
.\getLog.cmd
.\httpPinger.cmd
.\isContinue.vbs
.\new_sirius.ico
.\rar.exe
.\regionalSettings.ini
.\fonts\*
.\server.xml
.\Setup.cmd
.\setup_jre.exe
.\setup_tomcat.exe
.\sirius
.\sirius_agent.reg
.\tcnative-1.dll
.\TellMe.reg
.\wmic.js
.\resources.rar
.\sirius-atm.properties
.\sirius-atm.war
.\siriusTools.js